# Generated by Django 4.1 on 2022-11-18 13:37

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='file',
            field=models.FileField(upload_to=main.models.rename_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
