# Generated by Django 4.1 on 2023-03-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_agreement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='imagem_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/fabricantes/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_produto',
            field=models.ImageField(blank=True, null=True, upload_to='images/produtos/'),
        ),
    ]
